# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa770869fef98e2d465e043d0e0e2c7a946495edc22175f571defe2de4d13db669ef7a7988b7baca26aa594cc8c35278913406c23c72b435386a759ba70a5032

test:
  secret_key_base: 4ae1a1bc5a0ed21d26af41ffbcd3904e270bd760cc479222e95a5dc2d43880209886396529fedbdb8b8f69a75df8fde6f1f947f5feb59fc5a44caa7ba999643a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
